package menu_commands

import org.scalatest.FunSpec
import org.scalatest.Matchers


class Menu_Test extends FunSpec with Matchers {

   describe("Monopoly Deal Simulation") {
    describe("has a menu") {

      //******* SHOW GAME AREA *******
      it("can show the game area, including the players, player hands, money piles, and property collections") {
        val expectedResult =
          "Board: (Will look much better once GUI is implemented)\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"

        Menu.showGameArea should be(expectedResult)
      }

      
      //******* SHOW PLAYER ORDER *******
      it("can show the player order") {
        val expectedResult = "Emma, Rocco, Grace, Erik"
        Menu.showPlayerOrder should be(expectedResult)
      }

      //******* ADVANCE ORDER *******
      it("can advance the player order") {
        val expectedResult_0_advances = "Emma, Rocco, Grace, Erik"
        val expectedResult_1_advances = "Rocco, Grace, Erik, Emma"
        val expectedResult_2_advances = "Grace, Erik, Emma, Rocco"
        val expectedResult_4_advances = "Emma, Rocco, Grace, Erik"

        Menu.showPlayerOrder should be(expectedResult_0_advances)

        Menu.advancePlayerOrder 
        Menu.showPlayerOrder should be(expectedResult_1_advances)

        Menu.advancePlayerOrder
        Menu.showPlayerOrder should be(expectedResult_2_advances)

        Menu.advancePlayerOrder   // 3 advances
        Menu.advancePlayerOrder
        Menu.showPlayerOrder should be(expectedResult_4_advances)
        Menu.showPlayerOrder should be(expectedResult_0_advances)
      }
      
      
      //******* INITIALIZE GAME *******
      
      it("can INITIALIZE to reset the game board, player data, and deck") {
        Menu.initialize
        val expectedResult2 = 
          "Board: (Will look much better once GUI is implemented)\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][     Money     (a): $3m ][Red Ilnois Ave (p): $3m ][    Property   (a): $3m ][P Wld: Blu/Grn (p): $4m ][    -Money-    (m): $5m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[    -Money-    (m): $10m][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Pnk States Ave (p): $2m ]\n"+
"[Ylw Ventnr Ave (p): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Property   (a): $3m ]\n"+
"[P Wld: Grn/RRd (p): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][     Money     (a): $2m ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Org NwYork Ave (p): $2m ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Property   (a): $3m ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][P Wld: Cyn/Brn (p): $1m ][    Property   (a): $5m ][P Wld: Org/Pnk (p): $2m ][Blu Park Place (p): $4m ][    -Money-    (m): $4m ][                        ][                        ][                        ][                        ][                        ][                        ]\n"
        Menu.showGameArea should be(expectedResult2)
      }
      
      
      
      it("can DO MOVE, causing the player at the front of the player order to take a turn") {
        //Menu.initialize
        Menu.doMove
        //println("Hand: ")
        //for(c <- PlayerOrder.current.hand) println(c.name)
        //println("Props: ")
        //for(c <- PlayerOrder.current.properties) println(c.name)
        //println("Bank: ")
        //for(c <- PlayerOrder.current.bank) println(c.name)
        
        //println("AAA"+Menu.showGameArea)
        val expectedResultMove =
        "Board: (Will look much better once GUI is implemented)\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][     Money     (a): $3m ][    Property   (a): $3m ][    -Money-    (m): $5m ][    -Money-    (m): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][Red Ilnois Ave (p): $3m ][P Wld: Blu/Grn (p): $4m ][Pnk Virgin Ave (p): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[    -Money-    (m): $10m][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Pnk States Ave (p): $2m ]\n"+
"[Ylw Ventnr Ave (p): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Property   (a): $3m ]\n"+
"[P Wld: Grn/RRd (p): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][     Money     (a): $2m ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Org NwYork Ave (p): $2m ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Property   (a): $3m ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][P Wld: Cyn/Brn (p): $1m ][    Property   (a): $5m ][P Wld: Org/Pnk (p): $2m ][Blu Park Place (p): $4m ][    -Money-    (m): $4m ][                        ][                        ][                        ][                        ][                        ][                        ]\n"

        Menu.showGameArea should be(expectedResultMove)
      }
      
      //********* CHECK WINNER ************
      it("can check if the game has a winner (a player with 3 property sets)") {
        Menu.hasWinner should be(false)
      }
      
      //********* DO TURN ************
      it("can do a turn (each player does a move, checking for a winner each time)") {
        Menu.doTurn
        Menu.showGameArea
        
        val expectedResult = "Board: (Will look much better once GUI is implemented)\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Property   (a): $3m ][     Money     (a): $2m ][     Money     (a): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][Red Ilnois Ave (p): $3m ][P Wld: Blu/Grn (p): $4m ][Pnk Virgin Ave (p): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][            1x ( ): $1m ][            0x ( ): $2m ][            1x ( ): $3m ][            0x ( ): $4m ][            1x ( ): $5m ][            0x ( ): $10m][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][Ylw Ventnr Ave (p): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Pnk States Ave (p): $2m ][                        ]\n"+
"[                        ][P Wld: Grn/RRd (p): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Org NwYork Ave (p): $2m ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][P Wld: Ylw/Red (p): $3m ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Property   (a): $3m ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][     Money     (a): $2m ]\n"+
"[     Money     (a): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Property   (a): $3m ]\n"+
"[    -Money-    (m): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][     Money     (a): $3m ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][            1x ( ): $10m][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][            0x ( ): $5m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][            0x ( ): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][            0x ( ): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][            0x ( ): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][            0x ( ): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][P Wld: Cyn/Brn (p): $1m ][P Wld: Org/Pnk (p): $2m ][Blu Park Place (p): $4m ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    -Money-    (m): $3m ][RRd Readng RRd (p): $2m ][    Property   (a): $5m ][    -Money-    (m): $4m ][                        ][                        ][                        ][                        ][                        ][                        ]\n"
        
        Menu.showGameArea should be(expectedResult)
      }
      
      //*********DO GAME***********************
      it("can do a game that ends when a player wins") {
        val expectedResult = "Rocco"
        Menu.doGame should be (expectedResult)
      }
      
      //*********SET STRATEGY***********************
      it("can assign a specific strategy to a player") {
        val expectedResult = "Property Last"
        val apl = new Agent_PropertyLast(PlayerOrder.current)
        Menu.setStrategy(PlayerOrder.current, apl)
        Menu.curStrategy should be (expectedResult)
      }
      
      //*********SHOW STRATEGIES***********************
      it("can show all players and their current strategy") {
        val expectedResult = "Current Player Strategies:\n"+
          "Erik: Offensive Money\n"+
          "Emma: Property First\n"+
          "Rocco: Property Last\n"+
          "Grace: Offensive Property\n"
        Menu.advancePlayerOrder
        val aop = new Agent_OffensiveProperty(PlayerOrder.current)
        Menu.setStrategy(PlayerOrder.current, aop)
        Menu.advancePlayerOrder
        val aom = new Agent_OffensiveMoney(PlayerOrder.current)
        Menu.setStrategy(PlayerOrder.current, aom)
        Menu.showStrategies should be (expectedResult)
      }
      
      //*********DO STRATEGY GAME***********************
      it("can do a game with different strategies for each player, that ends when a player wins") {
        val expectedResult = "Rocco"
        Menu.initialize
        Menu.doGame should be (expectedResult)
      }
 
      
    }
    //Deck.debug
    
  }
}

