package menu_commands

import org.scalatest.FunSpec
import org.scalatest.Matchers


class Menu_Test extends FunSpec with Matchers {

   describe("Monopoly Deal Simulation") {
    describe("has a menu") {

      //******* SHOW GAME AREA *******
      it("can show the game area, including the players, player hands, money piles, and property collections") {
        val expectedResult =
          "Board: (Will look much better once GUI is implemented)\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
          "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"

        Menu.showGameArea should be(expectedResult)
      }

      
      //******* SHOW PLAYER ORDER *******
      it("can show the player order") {
        val expectedResult = "Emma, Rocco, Grace, Erik"
        Menu.showPlayerOrder should be(expectedResult)
      }

      //******* ADVANCE ORDER *******
      it("can advance the player order") {
        val expectedResult_0_advances = "Emma, Rocco, Grace, Erik"
        val expectedResult_1_advances = "Rocco, Grace, Erik, Emma"
        val expectedResult_2_advances = "Grace, Erik, Emma, Rocco"
        val expectedResult_4_advances = "Emma, Rocco, Grace, Erik"

        Menu.showPlayerOrder should be(expectedResult_0_advances)

        Menu.advancePlayerOrder 
        Menu.showPlayerOrder should be(expectedResult_1_advances)

        Menu.advancePlayerOrder
        Menu.showPlayerOrder should be(expectedResult_2_advances)

        Menu.advancePlayerOrder   // 3 advances
        Menu.advancePlayerOrder
        Menu.showPlayerOrder should be(expectedResult_4_advances)
        Menu.showPlayerOrder should be(expectedResult_0_advances)
      }
      
      
      //******* INITIALIZE GAME *******
      
      it("can INITIALIZE to reset the game board, player data, and deck") {
        Menu.initialize
        val expectedResult2 = 
          "Board: (Will look much better once GUI is implemented)\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][  My Birthday  (a): $2m ][P Wld: Grn/RRd (p): $4m ][    -Money-    (m): $4m ][  Double Rent  (a): $1m ][    Hotel      (a): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[   Sly Deal    (a): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][   Pass Go     (a): $1m ]\n"+
"[    -Money-    (m): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][   Pass Go     (a): $1m ]\n"+
"[Red Ilnois Ave (p): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Org Tennes Ave (p): $2m ]\n"+
"[Cyn Vermnt Ave (p): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    House      (a): $3m ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][P Wld: Cyn/Brn (p): $1m ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][ Rent: Grn/Blu (a): $1m ][    -Money-    (m): $2m ][RRd B & O RRd  (p): $2m ][    Hotel      (a): $4m ][ Rent: RRd/Utl (a): $1m ][                        ][                        ][                        ][                        ][                        ][                        ]\n"
        Menu.showGameArea should be(expectedResult2)
      }
      
      
      
      it("can DO MOVE, causing the player at the front of the player order to take a turn") {
        //Menu.initialize
        Menu.doMove
        //println("Hand: ")
        //for(c <- PlayerOrder.current.hand) println(c.name)
        //println("Props: ")
        //for(c <- PlayerOrder.current.properties) println(c.name)
        //println("Bank: ")
        //for(c <- PlayerOrder.current.bank) println(c.name)
        
        //println("AAA"+Menu.showGameArea)
        val expectedResultMove =
        "Board: (Will look much better once GUI is implemented)\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][  My Birthday  (a): $2m ][  Double Rent  (a): $1m ][    Hotel      (a): $4m ][    -Money-    (m): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][P Wld: Grn/RRd (p): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][            0x ( ): $1m ][            0x ( ): $2m ][            0x ( ): $3m ][            2x ( ): $4m ][            0x ( ): $5m ][            0x ( ): $10m][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[   Sly Deal    (a): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][   Pass Go     (a): $1m ]\n"+
"[    -Money-    (m): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][   Pass Go     (a): $1m ]\n"+
"[Red Ilnois Ave (p): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Org Tennes Ave (p): $2m ]\n"+
"[Cyn Vermnt Ave (p): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    House      (a): $3m ]\n"+
"[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][P Wld: Cyn/Brn (p): $1m ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
"[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][ Rent: Grn/Blu (a): $1m ][    -Money-    (m): $2m ][RRd B & O RRd  (p): $2m ][    Hotel      (a): $4m ][ Rent: RRd/Utl (a): $1m ][                        ][                        ][                        ][                        ][                        ][                        ]\n"  

        Menu.showGameArea should be(expectedResultMove)
      }
      
      //********* CHECK WINNER ************
      it("can check if the game has a winner (a player with 3 property sets)") {
        Menu.hasWinner should be(false)
      }
      
      //********* DO TURN ************
      it("can do a turn (each player does a move, checking for a winner each time)") {
        Menu.doTurn
        Menu.showGameArea
        
        val expectedResult = "Board: (Will look much better once GUI is implemented)\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][    Hotel      (a): $4m ][   Sly Deal    (a): $3m ][   Pass Go     (a): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][P Wld: Grn/RRd (p): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][            2x ( ): $1m ][            1x ( ): $2m ][            0x ( ): $3m ][            2x ( ): $4m ][            0x ( ): $5m ][            0x ( ): $10m][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][Red Ilnois Ave (p): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Org Tennes Ave (p): $2m ][                        ]\n"+
    "[                        ][Cyn Vermnt Ave (p): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][P Wld: Cyn/Brn (p): $1m ][                        ]\n"+
    "[                        ][Blu Park Place (p): $4m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Org NwYork Ave (p): $2m ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[   Sly Deal    (a): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][   Pass Go     (a): $1m ]\n"+
    "[    -Money-    (m): $3m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][   Pass Go     (a): $1m ]\n"+
    "[    -Money-    (m): $2m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][    House      (a): $3m ]\n"+
    "[ Rent: RRd/Utl (a): $1m ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][ Rent: Pnk/Org (a): $1m ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][            0x ( ): $1m ][            1x ( ): $2m ][            0x ( ): $3m ][            0x ( ): $4m ][            0x ( ): $5m ][            0x ( ): $10m][                        ][                        ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][Pnk States Ave (p): $2m ][RRd B & O RRd  (p): $2m ][                        ][                        ]\n"+
    "[                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][                        ][  Debt Cllctor (a): $3m ][ Rent: Grn/Blu (a): $1m ][    Hotel      (a): $4m ][ Rent: RRd/Utl (a): $1m ][                        ][                        ][                        ][                        ][                        ][                        ]\n"
        
        Menu.showGameArea should be(expectedResult)
      }
      
      //*********DO GAME***********************
      it("can do a game that ends when a player wins") {
        Menu.doGame should be ("Erik")
      }
      
    }
    Deck.debug
  }
}

